config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  get       "/signup",        to: "users#new"
  post      "/signup",        to: "users#create"
  get       "login",          to: "sessions#new"
  post      "login",          to: "sessions#create"
  delete    "logout",         to: "sessions#destroy"
  post      "accept",         to: "invitations#accept"
  delete    "decline",        to: "invitations#destroy"
  resources :users, only: [:create, :new, :show]
  resources :sessions, only: [:create, :new, :destroy]
  resources :events, only: [:create, :new, :index, :show]
  resources :invitations,  only: [:create, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :invitations
  has_many :attendees, through: :invitations, source: :user

  def invite(user)
    self.invitations.build(user_id: user.id).save unless invitation_exists(user)
  end

  # returns a relations containing all users who accepted their event invite
  def accepted_invitations
    User.joins(:attended_events).where( invitations: { accepted: true, event_id: self.id } )
  end

  def self.upcoming
    self.where("date >= ?", Time.now)
  end

  def self.past
    self.where("date < ?", Time.now)
  end

  private
    def invitation_exists(user)
      !Invitation.where(event_id: self.id, user_id: user.id).empty?
    end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: "creator_id"
  has_many :invitations
  has_many :attended_events, through: :invitations, source: :event

  # def attend(event)
  #   event.invitations.build(user_id: self.id, accepted: true).save
  # end
  def accept(invitation)
    invitation.update_attribute(:accepted, true)
  end

  def pending_invitations
    Invitation.joins(:user).where(accepted: false, user_id: self.id)
  end

  def upcoming_events
    Event.joins(:attendees).where( invitations: { accepted: true, user_id: self.id } ).where("date >= ?", Time.now)
  end

  def past_events
    Event.joins(:attendees).where( invitations: { accepted: true, user_id: self.id } ).where("date <= ?", Time.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      Invitation.new(user_id: current_user.id, event_id: @event.id, accepted: true).save
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.accepted_invitations
  end
end

private
  def event_params
    params.require(:event).permit(:title, :date, :location, :description)
  end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
  end

  def create
    @event = Event.find(event_params[:event_id])
    @user = User.find_by(invitation_params)
    if @user && @event
      @event.invite @user
    end
    redirect_to @event
  end

  def destroy
    invitation = Invitation.find invitation_params[:id]
    invitation.delete if current_user == invitation.user
    redirect_to current_user
  end

  def accept
    invitation = Invitation.find invitation_params[:id]
    current_user.accept invitation if current_user == invitation.user
    redirect_to current_user
  end

  private
    def event_params
      params.require(:event).permit(:event_id)
    end

    def invitation_params
      params.require(:invitation).permit(:id, :name)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user
      log_in @user
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @pending_invitations = @user.pending_invitations
    @upcoming_events = @user.upcoming_events
    @past_events = @user.past_events
  end

  private
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
    current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    @current_user = nil
    session.delete :user_id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user=(user)
    @current_user = user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<%= link_to event do %>
  <div class="event-card <%= status %>">
    <h5 class="event-title"><%= event.title %></h5>
    <h6 class="event-details">
      <%= event.date.strftime("%A %B %d, %Y") %> at <%= event.location %>
    </h6>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="container">
  <h1>Events</h1>
  <%= render "shared/event_list" %>
</div>

app/views/events/new.html.erb
<div class="container col-md-6">

  <h1>Create a new event</h1>
  <%= form_with scope: :event, url: events_path, local: true do |f| %>

    <% unless @event.errors.empty? %>
      <ul class="alert alert-danger">
        <% @user.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :date %>
      <%= f.date_field :date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :location, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Create event", class: "btn btn-primary form-control" %>
    </div>

  <% end %>

</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <h1><%= @event.title %></h1>
      <h6 class="event-details">Created by <%= @event.creator.name %></h6>
      <h6 class="event-details"><%=@event.date.strftime("%A %B %d, %Y")%> at <%= @event.location %></h6>
      <p class="event-description"><%= @event.description%></p>
    </div>

    <div class="col-md">
      <% if current_user == @event.creator %>
        <%= link_to "Invite Friends", new_invitation_path(params: { event_id: @event.id }), class: "btn btn-primary" %>
      <% end %>

      <h2> Attendees </h2>
      <ul>
        <% @attendees.each do |attendee| %>
          <li><%= link_to attendee.name, user_path(attendee) %></li>
        <% end %>
      </ul>
    </div>

  </div>
</div>

app/views/invitations/_invitation.html.erb
<div class="invitation-card">
  <p>You are invited to <%= link_to invitation.event.title, event_path(invitation.event_id) %>.</p>
  <%= link_to "Accept", accept_path(invitation: {id: invitation.id }), method: :post %>
  <%= link_to "Decline", decline_path(invitation: {id: invitation.id }), method: :delete %>
</div>

app/views/invitations/create.html.erb
<h1>Invitations#create</h1>
<p>Find me in app/views/invitations/create.html.erb</p>

app/views/invitations/new.html.erb
<div class="container col-md-6">
  <h1>Create an invitation</h1>
  <%= form_with scope: :invitation, url: invitations_path, local: true do |f| %>
    <%= hidden_field_tag "event[event_id]", params[:event_id] %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Send Invitation", class: "form-control btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "private-events", root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav ml-auto justify-content-end">
      <% if logged_in?%>
        <li class="nav-item"><%= link_to "New Event", new_event_path, class: "nav-link btn btn-outline-secondary" %></li>
        <li class="nav-item"><%= link_to current_user.name, user_path(current_user), class: "nav-link profile-link" %></li>
        <li class="nav-item"><%= link_to "Log Out", logout_path, method: :delete, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Log In", login_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Sign Up", signup_path, class: "nav-link btn btn-outline-secondary" %></li>
      <% end %>
    </ul>

  </div>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>PrivateEvents</title>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_event_list.html.erb
      <% unless @upcoming_events.empty? %>
        <h2>Upcoming Events</h2>
        <%= render @upcoming_events, status: "event-upcoming" %>
      <% end %>
      <% unless @past_events.empty?%>
        <h2>Past Events</h2>
        <%= render @past_events, status: "event-past" %>
      <% end %>

app/views/users/_signup_form.html.erb
<%= form_with scope: :user, url: signup_path, local: true do |f| %>

  <% unless @user.errors.empty? %>
    <ul class="alert alert-danger">
      <% @user.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create account", class: "btn btn-primary form-control" %>
  </div>

<% end %>

app/views/users/new.html.erb
<div class="container col-md-6">
  <h1>Create Account</h1>
  <h6>Enter your personal details to discover exclusive events near you.</h6>

  <%= render "signup_form" %>
</div>

app/views/users/show.html.erb
<div class="container">
  <% if current_user == @user %> <div class="row"> <% end %>

    <% if current_user == @user %>
      <div class="col-md-8">
    <% else %>
      <div class="col-md">
    <% end %>

      <% if current_user == @user && logged_in? %>
        <h1>Hello, <%= @user.name %></h1>
      <% else %>
        <h1><%= @user.name %></h1>
      <% end %>

      <% if @upcoming_events.empty? && @past_events.empty? %>
        <p>Hmm... <%= @user.name %> hasn't created any events yet.</p>
      <% else %>
        <%= render "shared/event_list" %>
      <% end %>
      </div>

      <% if current_user == @user %>
        <div class="col-md-4">
          <h2>Pending invitations</h2>
          <% unless @pending_invitations.empty? %>
            <%= render @pending_invitations %>
          <% else %>
            <p>You have no pending invitations.</p>
          <% end %>
        </div>
      <% end %>

  <% if current_user == @user %> </div> <% end %>
</div>